controllers:
    resource: ../src/Controller/
    type: attribute

# HOME
ajax_home_article_like:
    path: /ajax/verb/home/article_like/
    controller: App\Verb\Home\ArticleLikeHome::verbs
ajax_home_universe_menu:
    path: /ajax/universe/menu/
    controller: App\Verb\Home\UniverseHome::menu
ajax_home_infinite_scroll:
    path: /ajax/universe/infinite_scroll/
    controller: App\Verb\Home\InfiniteHome::more
ajax_home_theme_color_update:
    path: /ajax/universe/theme_update/
    controller: App\Verb\Home\ThemeUpdateHome::update

# SIGN-IN
ajax_signin_login:
    path: /processor/signin/login/
    controller: App\Process\SigninProcess::sign_in

# ARTICLE
ajax_article_save_views:
    path: /ajax/verb/article/views/
    controller: App\Verb\Home\ArticleViewsHome::views
ajax_article_save_shares:
    path: /ajax/verb/article/share/
    controller: App\Verb\Home\ArticleViewsHome::views

