controllers:
    resource: ../src/Controller/
    type: attribute

# HOME
ajax_home_article_like:
    path: /ajax/verb/home/article_like/
    controller: App\Verb\Home\ArticleLikeHome::verbs
ajax_home_universe_menu:
    path: /ajax/universe/menu/
    controller: App\Verb\Home\UniverseHome::menu
ajax_home_infinite_scroll:
    path: /ajax/universe/infinite_scroll/
    controller: App\Verb\Home\InfiniteHome::more
ajax_home_theme_color_update:
    path: /ajax/universe/theme_update/
    controller: App\Verb\Home\ThemeUpdateHome::update

# SIGN-IN
ajax_signin_login:
    path: /processor/signin/login/
    controller: App\Process\SigninProcess::sign_in

# ARTICLE
ajax_article_save_views:
    path: /ajax/verb/article/views/
    controller: App\Verb\Home\ArticleViewsHome::views
ajax_article_save_shares:
    path: /ajax/verb/article/share/
    controller: App\Verb\Home\ArticleViewsHome::views
ajax_article_verbs:
    path: /ajax/verb/article/verbs/
    controller: App\Verb\Home\ArticleLikeHome::verbs
ajax_article_follows:
    path: /ajax/verb/article/follows/
    controller: App\Verb\Home\ArticleFollowHome::verbs
ajax_article_comment:
    path: /ajax/verb/article/comment/
    controller: App\Verb\Home\ArticleCommentHome::verbs

# PROFILE
ajax_article_hide_articles:
    path: /ajax/verb/profile/hide_article/
    controller: App\Verb\Home\ProfileVerbsHome::index
ajax_draft_delete_articles:
    path: /ajax/verb/draft/delete_draft/
    controller: App\Verb\Home\ProfileVerbsHome::index
ajax_saved_remove_articles:
    path: /ajax/verb/saved/remove_saved/
    controller: App\Verb\Home\ProfileVerbsHome::index
ajax_changes_on_bio:
    path: /ajax/verb/change/on_bio/
    controller: App\Verb\Profile\ChangeProfile::index
ajax_changes_on_cover:
    path: /ajax/verb/change/on_cover/
    controller: App\Verb\Profile\ChangeProfile::index

